# dobi build configuration file
# See <https://github.com/dnephin/dobi> for details.

meta:
    project: dsi-studio
    default: nvidia-base

env=config:
    variables:
        [
            DOCKER_CONFIG="~/.docker/config.json",
            QT5_BASE_URL="theshadowx/qt5",
            QT5_TAG="default_qt5_bionic@sha256:212060a7ce061529e79153199ca269b633f72f2e71ea9715fc9812e56021017b",
            # QT5_TAG="default_qt5_bionic",
        ]

image=qt5-base:
    image: theshadowx/qt5
    tags: [default_qt5_bionic@sha256:212060a7ce061529e79153199ca269b633f72f2e71ea9715fc9812e56021017b]
    # tags: [default_qt5_bionic]
    # image: "{env.QT5_BASE_URL}"
    # tags: ["{env.QT5_TAG}"]
    depends: [config]
    pull: "always"
    annotations:
        description: "Qt5 base image for all DSI builds"

image=nvidia-base:
    image: _dsi-nvidia-base
    context: ../opengl/base
    dockerfile: ../opengl/base/Dockerfile
    depends: [qt5-base]
    args:
        from: qt5-base
# job=build-cpu:
#     use: builder

# job=build-nvidia:
#     use: builder

